<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Request/" />
    <Folder Include="Response/" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ICAR.Scanner.DataAccess\ICAR.Scanner.DataAccess.csproj" />
  </ItemGroup>

</Project>
